kind: pipeline
type: docker
name: ci-cd-demo

volumes:
  - name: maven_local_repo
    host:
      path: /app/data/maven_local_repo

steps:
  - name: build
    image: maven:3-jdk-8
    volumes:
      - name: maven_local_repo
        path: /root/.m2
    commands:
      - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - mvn test -B
  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: 112.13.201.108
      username:
        from_secret: ssh_account
      password:
        from_secret: ssh_password
      port: 2022
      command_timeout: 30m
      script_stop: false
      script:
        - echo hello
        - echo world