pipeline:
#  docker:
#    image: plugins/docker
#    username: daixk1212
#    password: dxk19911212
#    repo: test
#    tags: latest
  build:
    image: iishoni-maven
    commands:
      - mvn clean -s $MAVEN_CONFIG/settings.xml
