pipeline:
  build:
    image: iishoni/maven
    volumes:
      - /data/maven:/root/.m2
      - /var/run/docker.sock:/var/run/docker.sock
#    environment:
#      - DOCKER_HOST=unix:///var/run/docker.sock
    commands:
      - mvn -s $MAVEN_SETTINGS/settings.xml clean package -DskipTests docker:build
#    docker:
#      image: plugins/docker
#      username: daixk1212
#      password: dxk?19911212