pipeline:
  clean:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - sh clean.sh ci-cd-demo
  build:
    image: quay.io/dxk19911212/iishoni-maven
    volumes:
      - /data/maven:/root/.m2
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - mvn -s $MAVEN_SETTINGS/settings.xml clean package dockerfile:build
  deploy:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker run -dit --name ci-cd-demo -v /app/cloud/logs:/app/cloud/logs -p 8080:8080 quay.io/dxk19911212/ci-cd-demo
  publish:
    image: quay.io/dxk19911212/iishoni-maven
    volumes:
      - /data/maven:/root/.m2
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - mvn dockerfile:push