pipeline:
  build:
    image: iishoni/maven
    volumes:
      - /data/maven:/root/.m2
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - mvn -s $MAVEN_SETTINGS/settings.xml clean package -DskipTests docker:build
  deploy:
    image: @project.artifactId@
    volumes:
      - /app/cloud/logs/:/app/cloud/logs/
#      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8010:8010
