kind: pipeline
type: docker
name: ci-java8

volumes:
  - name: maven_local_repo
    host:
      path: /app/data/maven_local_repo

steps:
  - name: build
    image: maven:3-jdk-8
    volumes:
      - name: maven_local_repo
        path: /root/.m2
    commands:
      - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - mvn test -B
  - name: send-wechat
      image: yakumioto/serverchan
      settings:
        key: SCU48558T164ff96a3316d8a22cacea21d66b5caed80baa044
        text: hello world
        desp: Send by ServerChan