pipeline:
  build:
    image: iishoni/maven
    volumes:
      - /data/maven:/root/.m2
#    environment:
#      - DOCKER_HOST=unix:///var/run/docker.sock
    commands:
      - mvn -s $MAVEN_SETTINGS/settings.xml clean package docker:build
  docker:
    image: plugins/docker
    username: daixk1212
    password: dxk?19911212