pipeline:
  build:
    image: quay.io/dxk19911212/iishoni-maven
    volumes:
      - /data/maven:/root/.m2
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - mvn -s $MAVEN_SETTINGS/settings.xml clean package docker:build -DpushImage
  deploy:
    image: quay.io/dxk19911212/ci-cd-demo
    volumes:
      - /app/cloud/logs/:/app/cloud/logs/
    ports:
      - 8010:8010