spring:
    application:
        name: @project.artifactId@
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://mysql.iishoni.com/blog?useUnicode=true&characterEncoding=utf8&useTimezone=true&serverTimezone=CTT&useSSL=false&allowMultiQueries=true
        username: root
        password: root

server:
    port: 8887

swagger:
    base-path: /**
    exclude-path: /error
